In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw_sales_data.csv", encoding="latin1")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9994, 21)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [7]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
df[df.duplicated()==True]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [9]:
df.duplicated().sum()

np.int64(0)

### Clean Column Names

In [10]:

df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df.columns = df.columns.str.replace("-","_")

df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

### Convert Date Columns

In [11]:
df['order_date'] = pd.to_datetime(df['order_date'] , errors='coerce')
df['ship_date'] = pd.to_datetime(df['ship_date'] , errors='coerce')

### Convert Date Columns

In [12]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_month_name'] = df['order_date'].dt.month_name()
df['order_quaterly'] = df['order_date'].dt.quarter

In [13]:
df.isnull().sum()

row_id              0
order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
customer_name       0
segment             0
country             0
city                0
state               0
postal_code         0
region              0
product_id          0
category            0
sub_category        0
product_name        0
sales               0
quantity            0
discount            0
profit              0
order_year          0
order_month         0
order_month_name    0
order_quaterly      0
dtype: int64

In [14]:
# checking null values 
df["postal_code"].isnull().sum()

np.int64(0)

In [15]:
df["postal_code"] = df["postal_code"].fillna(0)

In [16]:
# fixing null values droping null values 
df = df.dropna(subset=["order_date", "sales", "profit", "quantity"])

In [17]:
# duplicates rows will removed 
df = df.drop_duplicates()

In [18]:
df[['profit','sales']].head()

     profit     sales
0   41.9136  261.9600
1  219.5820  731.9400
2    6.8714   14.6200
3 -383.0310  957.5775
4    2.5164   22.3680

In [19]:
df["profit_margin"] = round((df["profit"] / df["sales"]) * 100, 2)

In [20]:
df["profit_margin"] = df["profit_margin"].replace([np.inf, -np.inf], 0)
df["profit_margin"] = df["profit_margin"].fillna(0)

In [21]:
df["shipping_days"] = (df["ship_date"] - df["order_date"]).dt.days

In [22]:
def sales_category(value):
    if value < 100:
        return "Low"
    elif value < 500:
        return "Medium"
    else:
        return "High"

df["sales_category"] = df["sales"].apply(sales_category)

In [23]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,quantity,discount,profit,order_year,order_month,order_month_name,order_quaterly,profit_margin,shipping_days,sales_category
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,2016,11,November,4,16.00,3,Medium
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,2016,11,November,4,30.00,3,High
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,2016,6,June,2,47.00,4,Low
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,2015,10,October,4,-40.00,7,High
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,2015,10,October,4,11.25,7,Low

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   row_id            9994 non-null   int64
 1   order_id          9994 non-null   object
 2   order_date        9994 non-null   datetime64[ns]
 3   ship_date         9994 non-null   datetime64[ns]
 4   ship_mode         9994 non-null   object
 5   customer_id       9994 non-null   object
 6   customer_name     9994 non-null   object
 7   segment           9994 non-null   object
 8   country           9994 non-null   object
 9   city              9994 non-null   object
 10  state             9994 non-null   object
 11  postal_code       9994 non-null   int64
 12  region            9994 non-null   object
 13  product_id        9994 non-null   object
 14  category          9994 non-null   object
 15  sub_category      9994 non-null   object
 16  product_name      9994 non-null   object
 17  sales             9994 non-null   float64
 18  quantity          9994 non-null   int64
 19  discount          9994 non-null   float64
 20  profit            9994 non-null   float64
 21  order_year        9994 non-null   int32
 22  order_month       9994 non-null   int32
 23  order_month_name  9994 non-null   object
 24  order_quaterly    9994 non-null   int32
 25  profit_margin     9994 non-null   float64
 26  shipping_days     9994 non-null   int64
 27  sales_category    9994 non-null   object
dtypes: datetime64[ns](2), float64(4), int32(3), int64(4), object(15)
memory usage: 2.0+ MB

In [25]:
df.describe()

,row_id,order_date,ship_date,postal_code,sales,quantity,discount,profit,order_year,order_month,order_quaterly,profit_margin,shipping_days
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896,2015.722233,7.809686,2.882329,12.031390,3.958175
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,2014.000000,1.000000,1.000000,-275.000000,0.000000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,2015.000000,5.000000,2.000000,7.500000,3.000000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,2016.000000,9.000000,3.000000,27.000000,4.000000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,2017.000000,11.000000,4.000000,36.250000,5.000000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,2017.000000,12.000000,4.000000,50.000000,7.000000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.123555,3.284654,1.058086,46.675436,1.747567

In [26]:
df.isnull().sum()

row_id              0
order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
customer_name       0
segment             0
country             0
city                0
state               0
postal_code         0
region              0
product_id          0
category            0
sub_category        0
product_name        0
sales               0
quantity            0
discount            0
profit              0
order_year          0
order_month         0
order_month_name    0
order_quaterly      0
profit_margin       0
shipping_days       0
sales_category      0
dtype: int64

In [27]:
df.to_csv("../data/cleaned_sales_data.csv", index=False)